# This is a basic workflow to help you get started with Actions

name: Q3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions : write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          touch Q3_archive_java.txt
          echo Roche Gabriel > Q3_archive_java.txt
          echo -e >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt
          git config user.email "gabirocher@icloud.com"
          git config user.name "TheCrafteur2015"
          git add Q3_archive_java.txt
          git commit -m "Mise à jour du fichier Q3_archive_java.txt"
          git push
