# This is a basic workflow to help you get started with Actions

name: Q5

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions : write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          file=Q5_archive_$(date +"%d-%m-%Y").txt
          touch $(pwd)/$file
          echo Roche Gabriel > $file
          echo -e >> $file
          [ -r Q5.java ] && cat Q5.java >> $file
          git config user.email "gabirocher@icloud.com"
          git config user.name "TheCrafteur2015"
          git add $file
          git commit -m "Mise à jour du fichier $file"
          git push
